toml-version = "v1.0.0"

[files]
include = ["**/*.toml"]
# Note: Schema store has no available schema for `.cargo/config.toml` yet, so we exclude linting for
# the file until one is available. See https://github.com/rust-lang/cargo/issues/12883.
exclude = ["tools/yscope-dev-utils/**", "build/**", ".cargo/config.toml"]

[format]

[lint]
[lint.rules]
dotted-keys-out-of-order = "warn"
key-empty = "warn"
tables-out-of-order = "warn"

[schema]
enabled = true
strict = true
catalog = {
  paths = [
    "tombi://json.schemastore.org/api/json/catalog.json",
    "https://json.schemastore.org/api/json/catalog.json",
  ],
}

[[schemas]]
path = "tombi://json.schemastore.org/tombi.json"
include = ["tombi.toml"]

[[schemas]]
path = "https://json.schemastore.org/pyproject.json"
include = ["pyproject.toml"]

[[schemas]]
path = "https://json.schemastore.org/ruff.json"
include = ["ruff.toml"]

[[schemas]]
path = "https://json.schemastore.org/cargo.json"
include = ["Cargo.toml"]
