[package]
name = "spider-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "spider_core"
path = "src/lib.rs"

[dependencies]
uuid = {  version = "1.19.0", features = ["v4", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.149"