name: "code-linting-checks"

on:
  pull_request:
  push:
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Remove default CMake installation in the runner"
        run: "rm '/usr/local/bin/cmake'"

      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"

      - name: "Install task"
        run: "npm install -g @go-task/cli@3.44.0"

      - name: "Install dev dependencies"
        run: "./tools/scripts/lib_install/linux/install-dev.sh"

      - name: "Log tool versions"
        run: |-
          cmake --version
          md5sum --version
          python --version
          tar --version
          task --version
          uv --version

      - name: "Install project dependencies "
        timeout-minutes: 10
        env:
          SPIDER_DEPS_MAX_PARALLELISM_PER_TASK: "1"
        run: "task deps:lib_install"

      # NOTE: We don't use the cache for scheduled runs so that they run lint:cpp-static-check
      # on all files.
      - if: "'schedule' != github.event_name"
        name: "Restore lint:cpp-static-check cache"
        id: "cache-restore-lint-cpp-static-check"
        uses: "actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684"
        with:
          path: |
            .task/checksum/lint-cpp-static-check
            .task/checksum/utils-cpp-lint-clang-tidy-*
            build/lint-clang-tidy
          key: "lint:check-cpp-static-on-ubuntu-latest"

      - run: "task lint:check -C $(nproc)"

      # Cache the source file checksums and the generated files (logs) for the
      # lint:cpp-static-check task, but only if it runs successfully on the main branch.
      # NOTE: If we don't cache the generated files, the task will re-run to generate them.
      - if: "'pull_request' != github.event_name && 'refs/heads/main' == github.ref"
        name: "Update lint:cpp-static-check cache"
        uses: "actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684"
        with:
          path: |
            .task/checksum/lint-cpp-static-check
            .task/checksum/utils-cpp-lint-clang-tidy-*
            build/lint-clang-tidy
          key: >-
            lint:check-cpp-static-on-ubuntu-latest-${{hashFiles(
              '.task/checksum/lint-cpp-static-check',
              '.task/checksum/utils-cpp-lint-clang-tidy-*',
              'build/lint-clang-tidy/**/*'
            )}}
